// @generated by Cratis. Source: Ante.Organization.Registration.RegisterOrganization. Time: 2026-09-28T19:52:21.3518960Z. Hash: 739868489D44725E1AA717C10D5FD5BD07C1560186A55DB9928398765F4EF3DD
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { SignupContextEntry } from '../../Contracts/Organization/SignupContextEntry';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for self-service organization registration, used when a user signs in via the host's `/register` entry point without an invitation.
 */
export interface IRegisterOrganization {

    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    acceptedLegalTerms?: boolean;

    /**
     * The version of the legal document set that was presented and accepted.
     */
    acceptedLegalVersion?: string;

    /**
     * The first name of the registering user.
     */
    firstName?: string;

    /**
     * The last name of the registering user.
     */
    lastName?: string;

    /**
     * The middle name of the registering user.
     */
    middleName?: string;

    /**
     * The name of the organization (tenant) to create.
     */
    organizationName?: string;

    /**
     * A client-generated identifier used as the event source id and as a correlation key for polling setup status - reuses {@link InvitationId}'s shape since self-service registration shares the same "submit, then watch status" flow as an invitation acceptance.
     */
    registrationId?: Guid;

    /**
     * Host-supplied context carried from the registration link (for example the offer or campaign). Keys not in `Ante:Registration:ContextKeys` are dropped; the host must treat what remains as untrusted input.
     */
    signupContext?: SignupContextEntry[];
}


/**
 * Command for self-service organization registration, used when a user signs in via the host's `/register` entry point without an invitation.
 */
export class RegisterOrganization extends Command<IRegisterOrganization> implements IRegisterOrganization {
    readonly route: string = '/api/organization/registration';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('acceptedLegalTerms', Boolean, false),
        new PropertyDescriptor('acceptedLegalVersion', String, false),
        new PropertyDescriptor('firstName', String, false),
        new PropertyDescriptor('lastName', String, false),
        new PropertyDescriptor('middleName', String, true),
        new PropertyDescriptor('organizationName', String, false),
        new PropertyDescriptor('registrationId', Guid, false),
        new PropertyDescriptor('signupContext', SignupContextEntry, true),
    ];

    private _acceptedLegalTerms!: boolean;
    private _acceptedLegalVersion!: string;
    private _firstName!: string;
    private _lastName!: string;
    private _middleName?: string;
    private _organizationName!: string;
    private _registrationId!: Guid;
    private _signupContext?: SignupContextEntry[];

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    get acceptedLegalTerms(): boolean {
        return this._acceptedLegalTerms;
    }

    set acceptedLegalTerms(value: boolean) {
        this._acceptedLegalTerms = value;
        this.propertyChanged('acceptedLegalTerms');
    }
    /**
     * The version of the legal document set that was presented and accepted.
     */
    get acceptedLegalVersion(): string {
        return this._acceptedLegalVersion;
    }

    set acceptedLegalVersion(value: string) {
        this._acceptedLegalVersion = value;
        this.propertyChanged('acceptedLegalVersion');
    }
    /**
     * The first name of the registering user.
     */
    get firstName(): string {
        return this._firstName;
    }

    set firstName(value: string) {
        this._firstName = value;
        this.propertyChanged('firstName');
    }
    /**
     * The last name of the registering user.
     */
    get lastName(): string {
        return this._lastName;
    }

    set lastName(value: string) {
        this._lastName = value;
        this.propertyChanged('lastName');
    }
    /**
     * The middle name of the registering user.
     */
    get middleName(): string | undefined {
        return this._middleName;
    }

    set middleName(value: string | undefined) {
        this._middleName = value;
        this.propertyChanged('middleName');
    }
    /**
     * The name of the organization (tenant) to create.
     */
    get organizationName(): string {
        return this._organizationName;
    }

    set organizationName(value: string) {
        this._organizationName = value;
        this.propertyChanged('organizationName');
    }
    /**
     * A client-generated identifier used as the event source id and as a correlation key for polling setup status - reuses {@link InvitationId}'s shape since self-service registration shares the same "submit, then watch status" flow as an invitation acceptance.
     */
    get registrationId(): Guid {
        return this._registrationId;
    }

    set registrationId(value: Guid) {
        this._registrationId = value;
        this.propertyChanged('registrationId');
    }
    /**
     * Host-supplied context carried from the registration link (for example the offer or campaign). Keys not in `Ante:Registration:ContextKeys` are dropped; the host must treat what remains as untrusted input.
     */
    get signupContext(): SignupContextEntry[] | undefined {
        return this._signupContext;
    }

    set signupContext(value: SignupContextEntry[] | undefined) {
        this._signupContext = value;
        this.propertyChanged('signupContext');
    }

    static use(initialValues?: IRegisterOrganization): [RegisterOrganization, SetCommandValues<IRegisterOrganization>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RegisterOrganization, IRegisterOrganization>(RegisterOrganization, initialValues);
    }
}
