// @generated by Cratis. Source: Ante.Organization.Registration.RegisterOrganization. Time: 2026-09-06T22:14:18.4263890Z. Hash: 75FD0405DBBDDCBEF2FCE82728B9EB4D9BDD07DD4D8536F1C87BE960F4B3D67C
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Command for self-service organization registration, used when a user signs in via the host's `/register` entry point without an invitation.
 */
export interface IRegisterOrganization {
    
    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    acceptedLegalTerms?: boolean;
    
    /**
     * The version of the legal document set that was presented and accepted.
     */
    acceptedLegalVersion?: string;
    
    /**
     * The first name of the registering user.
     */
    firstName?: string;
    
    /**
     * The last name of the registering user.
     */
    lastName?: string;
    
    /**
     * The middle name of the registering user.
     */
    middleName?: string;
    
    /**
     * The name of the organization (tenant) to create.
     */
    organizationName?: string;
    
    /**
     * A client-generated identifier used as the event source id and as a correlation key for polling setup status - reuses {@link InvitationId}'s shape since self-service registration shares the same "submit, then watch status" flow as an invitation acceptance.
     */
    registrationId?: Guid;
}

export class RegisterOrganizationValidator extends CommandValidator<IRegisterOrganization> {
    constructor() {
        super();
        this.ruleFor(c => c.firstName).notEmpty().withMessage('First name is required.');
        this.ruleFor(c => c.firstName).maxLength(100).withMessage('First name cannot be longer than 100 characters.');
        this.ruleFor(c => c.lastName).notEmpty().withMessage('Last name is required.');
        this.ruleFor(c => c.lastName).maxLength(100).withMessage('Last name cannot be longer than 100 characters.');
        this.ruleFor(c => c.middleName).maxLength(100).withMessage('Middle name cannot be longer than 100 characters.');
        this.ruleFor(c => c.organizationName).notEmpty().withMessage('Organization name is required.');
        this.ruleFor(c => c.organizationName).maxLength(50).withMessage('Organization name cannot be longer than 50 characters.');
    }
}

/**
 * Command for self-service organization registration, used when a user signs in via the host's `/register` entry point without an invitation.
 */
export class RegisterOrganization extends Command<IRegisterOrganization, Record<string, unknown>> implements IRegisterOrganization {
    readonly route: string = '/api/organization/registration';
    readonly validation: CommandValidator = new RegisterOrganizationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('acceptedLegalTerms', Boolean, false),
        new PropertyDescriptor('acceptedLegalVersion', String, false),
        new PropertyDescriptor('firstName', String, false),
        new PropertyDescriptor('lastName', String, false),
        new PropertyDescriptor('middleName', String, true),
        new PropertyDescriptor('organizationName', String, false),
        new PropertyDescriptor('registrationId', Guid, false),
    ];

    private _acceptedLegalTerms!: boolean;
    private _acceptedLegalVersion!: string;
    private _firstName!: string;
    private _lastName!: string;
    private _middleName?: string;
    private _organizationName!: string;
    private _registrationId!: Guid;

    constructor() {
        super(Object, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    get acceptedLegalTerms(): boolean {
        return this._acceptedLegalTerms;
    }

    set acceptedLegalTerms(value: boolean) {
        this._acceptedLegalTerms = value;
        this.propertyChanged('acceptedLegalTerms');
    }
    /**
     * The version of the legal document set that was presented and accepted.
     */
    get acceptedLegalVersion(): string {
        return this._acceptedLegalVersion;
    }

    set acceptedLegalVersion(value: string) {
        this._acceptedLegalVersion = value;
        this.propertyChanged('acceptedLegalVersion');
    }
    /**
     * The first name of the registering user.
     */
    get firstName(): string {
        return this._firstName;
    }

    set firstName(value: string) {
        this._firstName = value;
        this.propertyChanged('firstName');
    }
    /**
     * The last name of the registering user.
     */
    get lastName(): string {
        return this._lastName;
    }

    set lastName(value: string) {
        this._lastName = value;
        this.propertyChanged('lastName');
    }
    /**
     * The middle name of the registering user.
     */
    get middleName(): string | undefined {
        return this._middleName;
    }

    set middleName(value: string | undefined) {
        this._middleName = value;
        this.propertyChanged('middleName');
    }
    /**
     * The name of the organization (tenant) to create.
     */
    get organizationName(): string {
        return this._organizationName;
    }

    set organizationName(value: string) {
        this._organizationName = value;
        this.propertyChanged('organizationName');
    }
    /**
     * A client-generated identifier used as the event source id and as a correlation key for polling setup status - reuses {@link InvitationId}'s shape since self-service registration shares the same "submit, then watch status" flow as an invitation acceptance.
     */
    get registrationId(): Guid {
        return this._registrationId;
    }

    set registrationId(value: Guid) {
        this._registrationId = value;
        this.propertyChanged('registrationId');
    }

    static use(initialValues?: IRegisterOrganization): [RegisterOrganization, SetCommandValues<IRegisterOrganization>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<RegisterOrganization, IRegisterOrganization>(RegisterOrganization, initialValues);
    }
}
