// @generated by Cratis. Source: Ante.Contracts.Organization.SignupContextEntry. Time: 2026-09-28T19:52:21.3518960Z. Hash: 417FDCC630B8D3A1EE20FA3207E979B1EB7B4258AD2D95A2BDCB213EB750C04D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

/**
 * One key/value pair of signup context carried from the registration link.
 */
export class SignupContextEntry {

    /**
     * The query-string key.
     */
    @field(String)
    key!: string;

    /**
     * The query-string value.
     */
    @field(String)
    value!: string;
}
