// @generated by Cratis. Source: Ante.Contracts.Invitations.InvitationFlowType. Time: 2026-09-06T05:49:47.4789760Z. Hash: D7015AC71E9E5C3D7ADF40646FBB39417343A46BBB8EB16829F76B442A874B13
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Represents the type of invitation flow a user is going through.
 */
export enum InvitationFlowType {
    joinTenant = 0,
    createTenant = 1,
}
