// @generated by Cratis. Source: Ante.Invitations.HostOutcome.HostOutcomeView, Ante.Invitations.HostOutcome.HostOutcomeView. Time: 2026-09-15T10:48:34.0409414Z. Hash: 747C5AD9AD14F0C9D88FB40E28A969E5B8C77B2B3455D5CA9CB6FDE06DD216D2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';
import { HostOutcomeStatus } from './HostOutcomeStatus';

/**
 * Gets the host-reported outcome for a specific onboarding attempt.
 */
export interface ForAttemptParameters {
    
    /**
     * The invitation or registration identifier to look up.
    */
    attemptId: Guid;
}


/**
 * Gets the host-reported outcome for a specific onboarding attempt.
 */
export class ForAttempt extends QueryFor<HostOutcomeView, ForAttemptParameters> {
    readonly route: string = '/api/invitations/host-outcome/for-attempt';
    readonly queryName: string = 'Ante.Invitations.HostOutcome.HostOutcomeView.ForAttempt';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: HostOutcomeView = {} as HostOutcomeView;

    constructor() {
        super(HostOutcomeView, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'attemptId',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('attemptId', Guid, false),
    ];

    attemptId!: Guid;


    static use(args?: ForAttemptParameters): [QueryResultWithState<HostOutcomeView>, PerformQuery<ForAttemptParameters>, SetSorting] {
        return useQuery<HostOutcomeView, ForAttempt, ForAttemptParameters>(ForAttempt, args);
    }

    static useSuspense(args?: ForAttemptParameters): [QueryResultWithState<HostOutcomeView>, PerformQuery<ForAttemptParameters>, SetSorting] {
        return useSuspenseQuery<HostOutcomeView, ForAttempt, ForAttemptParameters>(ForAttempt, args);
    }

    static when(condition: boolean): QueryWhen<ForAttempt, HostOutcomeView, ForAttemptParameters> {
        return new QueryWhen<ForAttempt, HostOutcomeView, ForAttemptParameters>(ForAttempt, condition);
    }
}

/**
 * Represents the host-reported outcome visible to the verified owner of one onboarding attempt.
 */
export class HostOutcomeView {

    /**
     * The invitation or registration identifier the outcome is bound to.
     */
    @field(Guid)
    attemptId!: Guid;

    /**
     * Whether this Ante deployment has a host outcome backchannel configured at all - deployment-level configuration, not attempt-specific, so exposing it carries no existence-leak risk the way {@link Status} would.
     */
    @field(Boolean)
    isConfigured!: boolean;

    /**
     * The outcome as currently known.
     */
    @field(Number)
    status!: HostOutcomeStatus;

    /**
     * A stable, low-cardinality reason code accompanying a terminal result; empty otherwise.
     */
    @field(String)
    reasonCode!: string;
}
