// @generated by Cratis. Source: Ante.Invitations.HostOutcome.HostOutcomeStatus. Time: 2026-09-07T02:39:45.4949390Z. Hash: 866349FA71F7D34296BB32F6BAA1DC2D9535C34B00B0380D9FBAE2D1BA8CAD2D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * The outcome a host reports for a specific onboarding attempt, as visible to the attempt's verified owner.
 */
export enum HostOutcomeStatus {
    unknown = 0,
    pending = 1,
    succeeded = 2,
    failed = 3,
}
