// @generated by Cratis. Source: Ante.Invitations.UserSetup.UserSetupAcceptanceStatus. Time: 2026-09-06T05:49:47.4789760Z. Hash: DDA4C728761D33AA4779E4F6D25FAC9318252EB9226A2DE9984081C5563C26B1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Represents the current acceptance status for user setup onboarding.
 */
export enum UserSetupAcceptanceStatus {
    pending = 0,
    accepted = 1,
    timedOut = 2,
}
