// @generated by Cratis. Source: Ante.Invitations.UserSetup.AcceptInvitation, Ante.Invitations.UserSetup.UserSetupAcceptanceStatusView, Ante.Invitations.UserSetup.UserSetupAcceptanceStatusView. Time: 2026-09-06T05:49:47.4789760Z. Hash: 9B7A432C774959954087D5CA486AAE2F854262CF13B174768CFF7645BDCF28B7
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor, ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { UserSetupAcceptanceStatus } from './UserSetupAcceptanceStatus';

/**
 * Command for accepting an invitation to join an existing tenant.
 */
export interface IAcceptInvitation {
    
    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    acceptedLegalTerms?: boolean;
    
    /**
     * The version of the legal document set that was presented and accepted.
     */
    acceptedLegalVersion?: string;
    
    /**
     * The first name of the user being onboarded.
     */
    firstName?: string;
    
    /**
     * The invitation this user setup is for.
     */
    invitationId?: Guid;
    
    /**
     * The last name of the user being onboarded.
     */
    lastName?: string;
    
    /**
     * The middle name of the user being onboarded.
     */
    middleName?: string;
}

export class AcceptInvitationValidator extends CommandValidator<IAcceptInvitation> {
    constructor() {
        super();
        this.ruleFor(c => c.firstName).notEmpty().withMessage('First name is required.');
        this.ruleFor(c => c.lastName).notEmpty().withMessage('Last name is required.');
    }
}

/**
 * Command for accepting an invitation to join an existing tenant.
 */
export class AcceptInvitation extends Command<IAcceptInvitation, Record<string, unknown>> implements IAcceptInvitation {
    readonly route: string = '/api/invitations/user-setup';
    readonly validation: CommandValidator = new AcceptInvitationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('acceptedLegalTerms', Boolean, false),
        new PropertyDescriptor('acceptedLegalVersion', String, false),
        new PropertyDescriptor('firstName', String, false),
        new PropertyDescriptor('invitationId', Guid, false),
        new PropertyDescriptor('lastName', String, false),
        new PropertyDescriptor('middleName', String, true),
    ];

    private _acceptedLegalTerms!: boolean;
    private _acceptedLegalVersion!: string;
    private _firstName!: string;
    private _invitationId!: Guid;
    private _lastName!: string;
    private _middleName?: string;

    constructor() {
        super(Object, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    get acceptedLegalTerms(): boolean {
        return this._acceptedLegalTerms;
    }

    set acceptedLegalTerms(value: boolean) {
        this._acceptedLegalTerms = value;
        this.propertyChanged('acceptedLegalTerms');
    }
    /**
     * The version of the legal document set that was presented and accepted.
     */
    get acceptedLegalVersion(): string {
        return this._acceptedLegalVersion;
    }

    set acceptedLegalVersion(value: string) {
        this._acceptedLegalVersion = value;
        this.propertyChanged('acceptedLegalVersion');
    }
    /**
     * The first name of the user being onboarded.
     */
    get firstName(): string {
        return this._firstName;
    }

    set firstName(value: string) {
        this._firstName = value;
        this.propertyChanged('firstName');
    }
    /**
     * The invitation this user setup is for.
     */
    get invitationId(): Guid {
        return this._invitationId;
    }

    set invitationId(value: Guid) {
        this._invitationId = value;
        this.propertyChanged('invitationId');
    }
    /**
     * The last name of the user being onboarded.
     */
    get lastName(): string {
        return this._lastName;
    }

    set lastName(value: string) {
        this._lastName = value;
        this.propertyChanged('lastName');
    }
    /**
     * The middle name of the user being onboarded.
     */
    get middleName(): string | undefined {
        return this._middleName;
    }

    set middleName(value: string | undefined) {
        this._middleName = value;
        this.propertyChanged('middleName');
    }

    static use(initialValues?: IAcceptInvitation): [AcceptInvitation, SetCommandValues<IAcceptInvitation>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<AcceptInvitation, IAcceptInvitation>(AcceptInvitation, initialValues);
    }
}

/**
 * Gets the user setup acceptance status for a specific invitation.
 */
export interface StatusForInvitationParameters {
    
    /**
     * The invitation identifier.
     */
    invitationId: Guid;
}


/**
 * Gets the user setup acceptance status for a specific invitation.
 */
export class StatusForInvitation extends ObservableQueryFor<UserSetupAcceptanceStatusView, StatusForInvitationParameters> {
    readonly route: string = '/api/invitations/user-setup/status-for-invitation';
    readonly queryName: string = 'Ante.Invitations.UserSetup.UserSetupAcceptanceStatusView.StatusForInvitation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: UserSetupAcceptanceStatusView = {} as any;

    constructor() {
        super(UserSetupAcceptanceStatusView, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'invitationId',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('invitationId', Guid, false),
    ];

    invitationId!: Guid;


    static use(args?: StatusForInvitationParameters): [QueryResultWithState<UserSetupAcceptanceStatusView>] {
        const [result] = useObservableQuery<UserSetupAcceptanceStatusView, StatusForInvitation, StatusForInvitationParameters>(StatusForInvitation, args);
        return [result];
    }

    static useSuspense(args?: StatusForInvitationParameters): [QueryResultWithState<UserSetupAcceptanceStatusView>] {
        const [result] = useSuspenseObservableQuery<UserSetupAcceptanceStatusView, StatusForInvitation, StatusForInvitationParameters>(StatusForInvitation, args);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<StatusForInvitation, UserSetupAcceptanceStatusView, StatusForInvitationParameters> {
        return new ObservableQueryWhen<StatusForInvitation, UserSetupAcceptanceStatusView, StatusForInvitationParameters>(StatusForInvitation, condition);
    }
}

/**
 * Represents the current user setup acceptance status.
 */
export class UserSetupAcceptanceStatusView {

    /**
     * The invitation identifier.
     */
    @field(Guid)
    invitationId!: Guid;

    /**
     * The acceptance status.
     */
    @field(Number)
    status!: UserSetupAcceptanceStatus;
}
