// @generated by Cratis. Source: Ante.Invitations.UserSetup.UserSetupAcceptanceStatus. Time: 2026-09-07T00:01:18.8413020Z. Hash: 07240BF74A2CE733F4289B6271BBA68E1A78D8F1EA7CDDE82A33078B6A1D963A
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Represents the current acceptance status for user setup onboarding.
 */
export enum UserSetupAcceptanceStatus {
    pending = 0,
    recorded = 1,
    accepted = 2,
}
