// @generated by Cratis. Source: Ante.Legal.LegalDocumentStatus, Ante.Legal.LegalDocumentStatus. Time: 2026-09-06T05:49:47.4789760Z. Hash: 4F69EC18FBB69F528289C914F3A02E68A5FC2FF4F866981408ACA45B7EA1DEC1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Gets the current legal document status.
 */
export class Current extends QueryFor<LegalDocumentStatus> {
    readonly route: string = '/api/legal/current';
    readonly queryName: string = 'Ante.Legal.LegalDocumentStatus.Current';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: LegalDocumentStatus = {} as any;

    constructor() {
        super(LegalDocumentStatus, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<LegalDocumentStatus>, PerformQuery, SetSorting] {
        return useQuery<LegalDocumentStatus, Current>(Current);
    }

    static useSuspense(): [QueryResultWithState<LegalDocumentStatus>, PerformQuery, SetSorting] {
        return useSuspenseQuery<LegalDocumentStatus, Current>(Current);
    }

    static when(condition: boolean): QueryWhen<Current, LegalDocumentStatus> {
        return new QueryWhen<Current, LegalDocumentStatus>(Current, condition);
    }
}

/**
 * Response model exposing whether a host has legal documents configured, and if so, their current content and version - so the wizards know whether to show a terms step at all.
 */
export class LegalDocumentStatus {

    /**
     * Whether the host has a legal document source with something to present.
     */
    @field(Boolean)
    isConfigured!: boolean;

    /**
     * The terms and conditions, empty when not configured.
     */
    @field(String)
    termsAndConditions!: string;

    /**
     * The privacy policy, empty when not configured.
     */
    @field(String)
    privacyPolicy!: string;

    /**
     * The version currently presented, empty when not configured.
     */
    @field(String)
    version!: string;
}
