// @generated by Cratis. Source: Ante.Invitations.Receiving.PendingInvitationToCreateOrganization, Ante.Invitations.Receiving.PendingInvitationToJoin, Ante.Invitations.Receiving.PendingInvitationToCreateOrganization, Ante.Invitations.Receiving.PendingInvitationToJoin. Time: 2026-09-27T16:08:02.7385580Z. Hash: CD97CC5C0C92AD8BF5630E08772904BBAB5A121482FD1BD221E4B448117949E4
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';

/**
 * Gets only the pending create-organization invitation owned by this request.
 */
export class PendingCreateOrganizationForCurrentInvitee extends QueryFor<PendingInvitationToCreateOrganization> {
    readonly route: string = '/api/invitations/receiving/pending-create-organization-for-current-invitee';
    readonly queryName: string = 'Ante.Invitations.Receiving.PendingInvitationToCreateOrganization.PendingCreateOrganizationForCurrentInvitee';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: PendingInvitationToCreateOrganization = {} as PendingInvitationToCreateOrganization;

    constructor() {
        super(PendingInvitationToCreateOrganization, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<PendingInvitationToCreateOrganization>, PerformQuery, SetSorting] {
        return useQuery<PendingInvitationToCreateOrganization, PendingCreateOrganizationForCurrentInvitee>(PendingCreateOrganizationForCurrentInvitee);
    }

    static useSuspense(): [QueryResultWithState<PendingInvitationToCreateOrganization>, PerformQuery, SetSorting] {
        return useSuspenseQuery<PendingInvitationToCreateOrganization, PendingCreateOrganizationForCurrentInvitee>(PendingCreateOrganizationForCurrentInvitee);
    }

    static when(condition: boolean): QueryWhen<PendingCreateOrganizationForCurrentInvitee, PendingInvitationToCreateOrganization> {
        return new QueryWhen<PendingCreateOrganizationForCurrentInvitee, PendingInvitationToCreateOrganization>(PendingCreateOrganizationForCurrentInvitee, condition);
    }
}

/**
 * Gets only the pending join invitation owned by this request.
 */
export class PendingJoinForCurrentInvitee extends QueryFor<PendingInvitationToJoin> {
    readonly route: string = '/api/invitations/receiving/pending-join-for-current-invitee';
    readonly queryName: string = 'Ante.Invitations.Receiving.PendingInvitationToJoin.PendingJoinForCurrentInvitee';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: PendingInvitationToJoin = {} as PendingInvitationToJoin;

    constructor() {
        super(PendingInvitationToJoin, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<PendingInvitationToJoin>, PerformQuery, SetSorting] {
        return useQuery<PendingInvitationToJoin, PendingJoinForCurrentInvitee>(PendingJoinForCurrentInvitee);
    }

    static useSuspense(): [QueryResultWithState<PendingInvitationToJoin>, PerformQuery, SetSorting] {
        return useSuspenseQuery<PendingInvitationToJoin, PendingJoinForCurrentInvitee>(PendingJoinForCurrentInvitee);
    }

    static when(condition: boolean): QueryWhen<PendingJoinForCurrentInvitee, PendingInvitationToJoin> {
        return new QueryWhen<PendingJoinForCurrentInvitee, PendingInvitationToJoin>(PendingJoinForCurrentInvitee, condition);
    }
}

/**
 * Read model for a pending invitation to create a new organization.
 */
export class PendingInvitationToCreateOrganization {

    /**
     * The invitation identifier.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The invitation subject used for compliance encryption.
     */
    @field(Guid)
    subject!: Guid;

    /**
     * The email address of the invited user.
     */
    @field(String)
    email!: string;

    /**
     * The roles the user will hold in the new organization.
     */
    @field(String, true)
    roles!: string[];
}

/**
 * Read model for a pending invitation to join an existing tenant.
 */
export class PendingInvitationToJoin {

    /**
     * The invitation identifier.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The invitation subject used for compliance encryption.
     */
    @field(Guid)
    subject!: Guid;

    /**
     * The email address of the invited user.
     */
    @field(String)
    email!: string;

    /**
     * The name of the existing tenant the user is being invited to join.
     */
    @field(String)
    tenantName!: string;

    /**
     * The roles the user is being invited into.
     */
    @field(String, true)
    roles!: string[];
}
