// @generated by Cratis. Source: Ante.Invitations.Receiving.PendingInvitationToCreateOrganization, Ante.Invitations.Receiving.PendingInvitationToJoin, Ante.Invitations.Receiving.PendingInvitationToCreateOrganization, Ante.Invitations.Receiving.PendingInvitationToJoin. Time: 2026-09-06T05:49:47.4789760Z. Hash: BFACEF005466DB45C35163177F4089F2FFD2E797DFC4CE86E3C183D5FD415EAC
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field, Guid } from '@cratis/fundamentals';

class AllPendingInvitationsToCreateOrganizationSortBy {

    constructor(readonly query: AllPendingInvitationsToCreateOrganization) {
    }

}

class AllPendingInvitationsToCreateOrganizationSortByWithoutQuery {

}


/**
 * Gets all pending create-organization invitations.
 */
export class AllPendingInvitationsToCreateOrganization extends ObservableQueryFor<PendingInvitationToCreateOrganization[]> {
    readonly route: string = '/api/invitations/receiving/all-pending-invitations-to-create-organization';
    readonly queryName: string = 'Ante.Invitations.Receiving.PendingInvitationToCreateOrganization.AllPendingInvitationsToCreateOrganization';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: PendingInvitationToCreateOrganization[] = [];
    private readonly _sortBy: AllPendingInvitationsToCreateOrganizationSortBy;
    private static readonly _sortBy: AllPendingInvitationsToCreateOrganizationSortByWithoutQuery = new AllPendingInvitationsToCreateOrganizationSortByWithoutQuery();

    constructor() {
        super(PendingInvitationToCreateOrganization, true);
        this._sortBy = new AllPendingInvitationsToCreateOrganizationSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllPendingInvitationsToCreateOrganizationSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllPendingInvitationsToCreateOrganizationSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<PendingInvitationToCreateOrganization[]>, SetSorting] {
        return useObservableQuery<PendingInvitationToCreateOrganization[], AllPendingInvitationsToCreateOrganization>(AllPendingInvitationsToCreateOrganization, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PendingInvitationToCreateOrganization[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<PendingInvitationToCreateOrganization[], AllPendingInvitationsToCreateOrganization>(AllPendingInvitationsToCreateOrganization, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<PendingInvitationToCreateOrganization[]>, SetSorting] {
        return useSuspenseObservableQuery<PendingInvitationToCreateOrganization[], AllPendingInvitationsToCreateOrganization>(AllPendingInvitationsToCreateOrganization, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PendingInvitationToCreateOrganization[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<PendingInvitationToCreateOrganization[], AllPendingInvitationsToCreateOrganization>(AllPendingInvitationsToCreateOrganization, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: PendingInvitationToCreateOrganization) => unknown, sorting?: Sorting): ChangeSet<PendingInvitationToCreateOrganization> {
        return useChangeStream<PendingInvitationToCreateOrganization, AllPendingInvitationsToCreateOrganization>(AllPendingInvitationsToCreateOrganization, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllPendingInvitationsToCreateOrganization, PendingInvitationToCreateOrganization[]> {
        return new ObservableQueryWhen<AllPendingInvitationsToCreateOrganization, PendingInvitationToCreateOrganization[]>(AllPendingInvitationsToCreateOrganization, condition);
    }
}

class AllPendingInvitationsToJoinSortBy {

    constructor(readonly query: AllPendingInvitationsToJoin) {
    }

}

class AllPendingInvitationsToJoinSortByWithoutQuery {

}


/**
 * Gets all pending join-tenant invitations.
 */
export class AllPendingInvitationsToJoin extends ObservableQueryFor<PendingInvitationToJoin[]> {
    readonly route: string = '/api/invitations/receiving/all-pending-invitations-to-join';
    readonly queryName: string = 'Ante.Invitations.Receiving.PendingInvitationToJoin.AllPendingInvitationsToJoin';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: PendingInvitationToJoin[] = [];
    private readonly _sortBy: AllPendingInvitationsToJoinSortBy;
    private static readonly _sortBy: AllPendingInvitationsToJoinSortByWithoutQuery = new AllPendingInvitationsToJoinSortByWithoutQuery();

    constructor() {
        super(PendingInvitationToJoin, true);
        this._sortBy = new AllPendingInvitationsToJoinSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllPendingInvitationsToJoinSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllPendingInvitationsToJoinSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<PendingInvitationToJoin[]>, SetSorting] {
        return useObservableQuery<PendingInvitationToJoin[], AllPendingInvitationsToJoin>(AllPendingInvitationsToJoin, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PendingInvitationToJoin[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<PendingInvitationToJoin[], AllPendingInvitationsToJoin>(AllPendingInvitationsToJoin, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<PendingInvitationToJoin[]>, SetSorting] {
        return useSuspenseObservableQuery<PendingInvitationToJoin[], AllPendingInvitationsToJoin>(AllPendingInvitationsToJoin, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<PendingInvitationToJoin[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<PendingInvitationToJoin[], AllPendingInvitationsToJoin>(AllPendingInvitationsToJoin, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: PendingInvitationToJoin) => unknown, sorting?: Sorting): ChangeSet<PendingInvitationToJoin> {
        return useChangeStream<PendingInvitationToJoin, AllPendingInvitationsToJoin>(AllPendingInvitationsToJoin, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<AllPendingInvitationsToJoin, PendingInvitationToJoin[]> {
        return new ObservableQueryWhen<AllPendingInvitationsToJoin, PendingInvitationToJoin[]>(AllPendingInvitationsToJoin, condition);
    }
}

/**
 * Read model for a pending invitation to create a new organization.
 */
export class PendingInvitationToCreateOrganization {

    /**
     * The invitation identifier.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The invitation subject used for compliance encryption.
     */
    @field(Guid)
    subject!: Guid;

    /**
     * The email address of the invited user.
     */
    @field(String)
    email!: string;

    /**
     * The roles the user will hold in the new organization.
     */
    @field(String, true)
    roles!: string[];
}

/**
 * Read model for a pending invitation to join an existing tenant.
 */
export class PendingInvitationToJoin {

    /**
     * The invitation identifier.
     */
    @field(Guid)
    id!: Guid;

    /**
     * The invitation subject used for compliance encryption.
     */
    @field(Guid)
    subject!: Guid;

    /**
     * The email address of the invited user.
     */
    @field(String)
    email!: string;

    /**
     * The name of the existing tenant the user is being invited to join.
     */
    @field(String)
    tenantName!: string;

    /**
     * The roles the user is being invited into.
     */
    @field(String, true)
    roles!: string[];
}
