// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';
import eslint from '@eslint/js';
import typescriptEslint from '@typescript-eslint/eslint-plugin';
import tsParser from '@typescript-eslint/parser';
import header from '@tony.ganchev/eslint-plugin-header';
import noNull from 'eslint-plugin-no-null';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactlint from 'eslint-plugin-react';

header.rules.header.meta.schema = false;

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all,
});

const getRules = configArray => {
    let rules = {};

    const addRulesFromObject = config => {
        if (config.hasOwnProperty('rules')) {
            rules = {
                ...rules,
                ...config.rules,
            };
        }
    };

    if (Array.isArray(configArray)) {
        for (const config of configArray) {
            addRulesFromObject(config);
        }
    } else {
        addRulesFromObject(configArray);
    }

    return rules;
};

const rules = {
    ...getRules(eslint.configs.recommended),
    ...getRules(tseslint.configs.recommended),
    ...getRules(reactlint.configs.recommended),
    ...{
        'no-irregular-whitespace': 0,
        semi: [2, 'always'],
        'react/display-name': 0,
        'react/react-in-jsx-scope': 0,
        'react/prop-types': 0,
        'no-prototype-builtins': 0,

        '@typescript-eslint/no-unused-vars': [
            'error',
            {
                ignoreRestSiblings: true,
                argsIgnorePattern: '^_',
                varsIgnorePattern: '^_',
            },
        ],

        '@typescript-eslint/no-explicit-any': 'error',
        '@typescript-eslint/explicit-module-boundary-types': 0,
        '@typescript-eslint/no-non-null-assertion': 0,
        '@typescript-eslint/no-empty-function': 'error',
        '@typescript-eslint/no-var-requires': 'error',
        '@typescript-eslint/ban-ts-comment': 0,
        '@typescript-eslint/no-empty-interface': 0,
        // Generated command proxies for property-less commands emit an empty interface; this is the
        // renamed successor of the already-disabled no-empty-interface rule.
        '@typescript-eslint/no-empty-object-type': 0,

        '@tony.ganchev/header': [
            2,
            'line',
            [{
                pattern: '^( @generated by Cratis\\. | Copyright \\(c\\) Cratis\\. All rights reserved\\.\\n Licensed under the MIT license\\. See LICENSE file in the project root for full license information\\.)'
            }],
            1
        ],
    },
};

const defaultConfig = [
    {
        ignores: [
            '**/*.d.ts',
            '**/tsconfig.*',
            '**/*.js',
            '**/dist/**',
            '**/node_modules/**',
            '**/wwwroot/**',
            '**/AspNetCore/**',
            '**/vite.config.ts'
        ],
    },
    {
        files: ['**/*.ts', '**/*.tsx'],

        plugins: {
            '@typescript-eslint': typescriptEslint,
            react: reactlint,
            '@tony.ganchev': header,
            header: header,
            'no-null': noNull,
        },

        rules,

        languageOptions: {
            globals: {
                ...globals.browser,
            },
            parser: tsParser,
            sourceType: 'module',
        },

        settings: {
            react: {
                version: '19.2',
            },
        },
    },
    {
        files: ['**/for_*/**/*.ts'],
        rules: {
            '@typescript-eslint/naming-convention': 0,
            '@typescript-eslint/no-unused-expressions': 0,
            '@typescript-eslint/no-empty-function': 'off',
            'no-restricted-globals': 0,
        },
    },
    {
        // Proxies the Cratis generator emits use `any` in places, and rule 15 forbids editing a
        // generated file — so the ban is lifted for them and only them.
        files: [
            'Configuration/Configuration.ts',
            '**/Invitations/Accepting/Accepting.ts',
            '**/Invitations/HostOutcome/HostOutcome.ts',
            '**/Invitations/OrganizationSetup/OrganizationSetup.ts',
            '**/Invitations/UserSetup/UserSetup.ts',
            '**/Legal/LegalDocuments.ts',
            '**/Organization/Registration/Registration.ts',
        ],
        rules: {
            '@typescript-eslint/no-explicit-any': 'off',
        },
    },
    {
        // Barrel index files are pure re-exports and do not need a copyright header.
        files: ['**/index.ts', '**/index.tsx'],
        rules: {
            '@tony.ganchev/header': 'off',
        },
    },
];

const config = tseslint.config(...defaultConfig);
export default config;
