// @generated by Cratis. Source: Ante.Invitations.OrganizationSetup.SetupOrganization, Ante.Invitations.OrganizationSetup.OrganizationSetupAcceptanceStatusView, Ante.Invitations.OrganizationSetup.OrganizationSetupAcceptanceStatusView. Time: 2026-09-06T05:49:47.4789760Z. Hash: C6850063B84FAC3AD15E75408EEBFCFE875D474B4D4AB51CD8BE84460E114717
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor, ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid, field } from '@cratis/fundamentals';
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { OrganizationSetupAcceptanceStatus } from './OrganizationSetupAcceptanceStatus';

/**
 * Command for setting up a new tenant organization during the create-tenant invitation flow.
 */
export interface ISetupOrganization {
    
    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    acceptedLegalTerms?: boolean;
    
    /**
     * The version of the legal document set that was presented and accepted.
     */
    acceptedLegalVersion?: string;
    
    /**
     * The first name of the user being onboarded.
     */
    firstName?: string;
    
    /**
     * The invitation this organization setup is for.
     */
    invitationId?: Guid;
    
    /**
     * The last name of the user being onboarded.
     */
    lastName?: string;
    
    /**
     * The middle name of the user being onboarded.
     */
    middleName?: string;
    
    /**
     * The name of the organization (tenant) to create.
     */
    organizationName?: string;
}

export class SetupOrganizationValidator extends CommandValidator<ISetupOrganization> {
    constructor() {
        super();
        this.ruleFor(c => c.firstName).notEmpty().withMessage('First name is required.');
        this.ruleFor(c => c.lastName).notEmpty().withMessage('Last name is required.');
        this.ruleFor(c => c.organizationName).notEmpty().withMessage('Organization name is required.');
        this.ruleFor(c => c.organizationName).maxLength(50).withMessage('Organization name cannot be longer than 50 characters.');
    }
}

/**
 * Command for setting up a new tenant organization during the create-tenant invitation flow.
 */
export class SetupOrganization extends Command<ISetupOrganization, Record<string, unknown>> implements ISetupOrganization {
    readonly route: string = '/api/invitations/organization-setup';
    readonly validation: CommandValidator = new SetupOrganizationValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('acceptedLegalTerms', Boolean, false),
        new PropertyDescriptor('acceptedLegalVersion', String, false),
        new PropertyDescriptor('firstName', String, false),
        new PropertyDescriptor('invitationId', Guid, false),
        new PropertyDescriptor('lastName', String, false),
        new PropertyDescriptor('middleName', String, true),
        new PropertyDescriptor('organizationName', String, false),
    ];

    private _acceptedLegalTerms!: boolean;
    private _acceptedLegalVersion!: string;
    private _firstName!: string;
    private _invitationId!: Guid;
    private _lastName!: string;
    private _middleName?: string;
    private _organizationName!: string;

    constructor() {
        super(Object, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * Whether the user has accepted the terms and conditions and the privacy policy.
     */
    get acceptedLegalTerms(): boolean {
        return this._acceptedLegalTerms;
    }

    set acceptedLegalTerms(value: boolean) {
        this._acceptedLegalTerms = value;
        this.propertyChanged('acceptedLegalTerms');
    }
    /**
     * The version of the legal document set that was presented and accepted.
     */
    get acceptedLegalVersion(): string {
        return this._acceptedLegalVersion;
    }

    set acceptedLegalVersion(value: string) {
        this._acceptedLegalVersion = value;
        this.propertyChanged('acceptedLegalVersion');
    }
    /**
     * The first name of the user being onboarded.
     */
    get firstName(): string {
        return this._firstName;
    }

    set firstName(value: string) {
        this._firstName = value;
        this.propertyChanged('firstName');
    }
    /**
     * The invitation this organization setup is for.
     */
    get invitationId(): Guid {
        return this._invitationId;
    }

    set invitationId(value: Guid) {
        this._invitationId = value;
        this.propertyChanged('invitationId');
    }
    /**
     * The last name of the user being onboarded.
     */
    get lastName(): string {
        return this._lastName;
    }

    set lastName(value: string) {
        this._lastName = value;
        this.propertyChanged('lastName');
    }
    /**
     * The middle name of the user being onboarded.
     */
    get middleName(): string | undefined {
        return this._middleName;
    }

    set middleName(value: string | undefined) {
        this._middleName = value;
        this.propertyChanged('middleName');
    }
    /**
     * The name of the organization (tenant) to create.
     */
    get organizationName(): string {
        return this._organizationName;
    }

    set organizationName(value: string) {
        this._organizationName = value;
        this.propertyChanged('organizationName');
    }

    static use(initialValues?: ISetupOrganization): [SetupOrganization, SetCommandValues<ISetupOrganization>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<SetupOrganization, ISetupOrganization>(SetupOrganization, initialValues);
    }
}

/**
 * Gets the organization setup acceptance status for a specific invitation.
 */
export interface StatusForInvitationParameters {
    
    /**
     * The invitation identifier.
     */
    invitationId: Guid;
}


/**
 * Gets the organization setup acceptance status for a specific invitation.
 */
export class StatusForInvitation extends ObservableQueryFor<OrganizationSetupAcceptanceStatusView, StatusForInvitationParameters> {
    readonly route: string = '/api/invitations/organization-setup/status-for-invitation';
    readonly queryName: string = 'Ante.Invitations.OrganizationSetup.OrganizationSetupAcceptanceStatusView.StatusForInvitation';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: OrganizationSetupAcceptanceStatusView = {} as any;

    constructor() {
        super(OrganizationSetupAcceptanceStatusView, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'invitationId',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('invitationId', Guid, false),
    ];

    invitationId!: Guid;


    static use(args?: StatusForInvitationParameters): [QueryResultWithState<OrganizationSetupAcceptanceStatusView>] {
        const [result] = useObservableQuery<OrganizationSetupAcceptanceStatusView, StatusForInvitation, StatusForInvitationParameters>(StatusForInvitation, args);
        return [result];
    }

    static useSuspense(args?: StatusForInvitationParameters): [QueryResultWithState<OrganizationSetupAcceptanceStatusView>] {
        const [result] = useSuspenseObservableQuery<OrganizationSetupAcceptanceStatusView, StatusForInvitation, StatusForInvitationParameters>(StatusForInvitation, args);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<StatusForInvitation, OrganizationSetupAcceptanceStatusView, StatusForInvitationParameters> {
        return new ObservableQueryWhen<StatusForInvitation, OrganizationSetupAcceptanceStatusView, StatusForInvitationParameters>(StatusForInvitation, condition);
    }
}

/**
 * Represents the current organization setup acceptance status.
 */
export class OrganizationSetupAcceptanceStatusView {

    /**
     * The invitation identifier.
     */
    @field(Guid)
    invitationId!: Guid;

    /**
     * The live acceptance status.
     */
    @field(Number)
    status!: OrganizationSetupAcceptanceStatus;

    /**
     * The name of the organization being set up; empty until known.
     */
    @field(String)
    organizationName!: string;
}
