// @generated by Cratis. Source: Ante.Invitations.OrganizationSetup.OrganizationSetupAcceptanceStatus. Time: 2026-09-07T00:01:18.8413020Z. Hash: F9D23980352909089D0D32683AA80AF2248A359B06DC99551589C58BC6458A48
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Represents the current acceptance status for organization setup onboarding.
 */
export enum OrganizationSetupAcceptanceStatus {
    pending = 0,
    recorded = 1,
    accepted = 2,
}
