// @generated by Cratis. Source: Ante.Invitations.OrganizationSetup.OrganizationSetupAcceptanceStatus. Time: 2026-09-06T05:49:47.4789760Z. Hash: 732483E7A95C59258C0BD675B7EE6F950560D877A1E88E602799706D0DADFE7D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
/**
 * Represents the current acceptance status for organization setup onboarding.
 */
export enum OrganizationSetupAcceptanceStatus {
    pending = 0,
    accepted = 1,
}
