// @generated by Cratis. Source: Ante.Organization.Registration.Start.BeginRegistration. Time: 2026-09-28T10:19:29.7722850Z. Hash: 863A732460CAFE9BBE0F7B4B116ED9D4A44D7E5A7844CEF04CB686C0824BEDB1
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

/**
 * Associates a client-generated registration id with its authenticated owner before showing the wizard.
 */
export interface IBeginRegistration {

    /**
     * The registration's event source identifier.
     */
    registrationId?: Guid;
}


/**
 * Associates a client-generated registration id with its authenticated owner before showing the wizard.
 */
export class BeginRegistration extends Command<IBeginRegistration, Record<string, unknown>> implements IBeginRegistration {
    readonly route: string = '/api/organization/registration/start';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('registrationId', Guid, false),
    ];

    private _registrationId!: Guid;

    constructor() {
        super(Object, true);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * The registration's event source identifier.
     */
    get registrationId(): Guid {
        return this._registrationId;
    }

    set registrationId(value: Guid) {
        this._registrationId = value;
        this.propertyChanged('registrationId');
    }

    static use(initialValues?: IBeginRegistration): [BeginRegistration, SetCommandValues<IBeginRegistration>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<BeginRegistration, IBeginRegistration>(BeginRegistration, initialValues);
    }
}
