// @generated by Cratis. Source: Ante.Invitations.Accepting.InviteExchangeController, Ante.Invitations.Accepting.InvitationIdentityDetails. Time: 2026-09-06T05:49:47.4789760Z. Hash: 45E24B7A0825C08AB81ED4325F30620E6277C4F928AF7BE90AEBB19E0EFC6A15
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { IActionResult } from '../../AspNetCore/Mvc/IActionResult';
import { field, Guid } from '@cratis/fundamentals';
import { InvitationFlowType } from '../../Contracts/Invitations/InvitationFlowType';

/**
 * Exchanges an invitation token for a recorded acceptance session.
 */
export interface IExchange {
    
    /**
     * What the authentication proxy can say about the provider the user authenticated with - its `iss` claim, or nothing at all for an OAuth2-only provider, which issues none. It is resolved against the deployment's configured providers rather than recorded verbatim.
     */
    identityProvider?: string;
    
    /**
     * The normalized issuer of the canonical federated identity, sent alongside the key.
     */
    issuer?: string;
    
    /**
     * The canonical provider key, sent only when the authentication proxy is configured to resolve a canonical federated identity for the provider. It is the one value that names a federated provider outright, so it is preferred over everything else when present.
     */
    providerKey?: string;
    
    /**
     * The subject (`sub`) claim of the authenticated user.
     */
    subject?: string;
}


/**
 * Exchanges an invitation token for a recorded acceptance session.
 */
export class Exchange extends Command<IExchange, IActionResult> implements IExchange {
    readonly route: string = '/_invite/exchange';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('identityProvider', String, false),
        new PropertyDescriptor('issuer', String, true),
        new PropertyDescriptor('providerKey', String, true),
        new PropertyDescriptor('subject', String, false),
    ];

    private _identityProvider!: string;
    private _issuer?: string;
    private _providerKey?: string;
    private _subject!: string;

    constructor() {
        super(IActionResult, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    /**
     * What the authentication proxy can say about the provider the user authenticated with - its `iss` claim, or nothing at all for an OAuth2-only provider, which issues none. It is resolved against the deployment's configured providers rather than recorded verbatim.
     */
    get identityProvider(): string {
        return this._identityProvider;
    }

    set identityProvider(value: string) {
        this._identityProvider = value;
        this.propertyChanged('identityProvider');
    }
    /**
     * The normalized issuer of the canonical federated identity, sent alongside the key.
     */
    get issuer(): string | undefined {
        return this._issuer;
    }

    set issuer(value: string | undefined) {
        this._issuer = value;
        this.propertyChanged('issuer');
    }
    /**
     * The canonical provider key, sent only when the authentication proxy is configured to resolve a canonical federated identity for the provider. It is the one value that names a federated provider outright, so it is preferred over everything else when present.
     */
    get providerKey(): string | undefined {
        return this._providerKey;
    }

    set providerKey(value: string | undefined) {
        this._providerKey = value;
        this.propertyChanged('providerKey');
    }
    /**
     * The subject (`sub`) claim of the authenticated user.
     */
    get subject(): string {
        return this._subject;
    }

    set subject(value: string) {
        this._subject = value;
        this.propertyChanged('subject');
    }

    static use(initialValues?: IExchange): [Exchange, SetCommandValues<IExchange>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<Exchange, IExchange>(Exchange, initialValues);
    }
}

/**
 * Application-level identity details for an invited user going through Ante.
 */
export class InvitationIdentityDetails {

    /**
     * The invitation identifier associated with this user session.
     */
    @field(Guid)
    invitationId!: Guid;

    /**
     * The type of invitation flow this user is going through.
     */
    @field(Number)
    flowType!: InvitationFlowType;
}
