// @generated by Cratis. Source: Ante.Configuration.HostAppUrlConfiguration, Ante.Configuration.HostAppUrlConfiguration, Ante.Configuration.BrandingConfiguration, Ante.Configuration.HostAppUrlConfiguration, Ante.Configuration.BrandingConfiguration. Time: 2026-09-06T05:49:47.4789760Z. Hash: B108665BD8691644DC3CDFA9A2DCBB294897CAA83B873C378BCAB8B704D61380
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Returns the {@link HostAppUrlConfiguration} based on the provided {@link AnteOptions} and the identity provider behind the current request.
 */
export class HostUrl extends QueryFor<HostAppUrlConfiguration> {
    readonly route: string = '/api/configuration/host-url';
    readonly queryName: string = 'Ante.Configuration.HostAppUrlConfiguration.HostUrl';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: HostAppUrlConfiguration = {} as any;

    constructor() {
        super(HostAppUrlConfiguration, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<HostAppUrlConfiguration>, PerformQuery, SetSorting] {
        return useQuery<HostAppUrlConfiguration, HostUrl>(HostUrl);
    }

    static useSuspense(): [QueryResultWithState<HostAppUrlConfiguration>, PerformQuery, SetSorting] {
        return useSuspenseQuery<HostAppUrlConfiguration, HostUrl>(HostUrl);
    }

    static when(condition: boolean): QueryWhen<HostUrl, HostAppUrlConfiguration> {
        return new QueryWhen<HostUrl, HostAppUrlConfiguration>(HostUrl, condition);
    }
}

export interface SignInPathForParameters {
    identityProvider?: string;
}


export class SignInPathFor extends QueryFor<string, SignInPathForParameters> {
    readonly route: string = '/api/configuration/sign-in-path-for';
    readonly queryName: string = 'Ante.Configuration.HostAppUrlConfiguration.SignInPathFor';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: string = {} as any;

    constructor() {
        super(String, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('identityProvider', String, false),
    ];

    identityProvider!: string;


    static use(args?: SignInPathForParameters): [QueryResultWithState<string>, PerformQuery<SignInPathForParameters>, SetSorting] {
        return useQuery<string, SignInPathFor, SignInPathForParameters>(SignInPathFor, args);
    }

    static useSuspense(args?: SignInPathForParameters): [QueryResultWithState<string>, PerformQuery<SignInPathForParameters>, SetSorting] {
        return useSuspenseQuery<string, SignInPathFor, SignInPathForParameters>(SignInPathFor, args);
    }

    static when(condition: boolean): QueryWhen<SignInPathFor, string, SignInPathForParameters> {
        return new QueryWhen<SignInPathFor, string, SignInPathForParameters>(SignInPathFor, condition);
    }
}

/**
 * Returns the {@link BrandingConfiguration} based on the provided {@link AnteOptions}.
 */
export class GetConfiguration extends QueryFor<BrandingConfiguration> {
    readonly route: string = '/api/configuration/get-configuration';
    readonly queryName: string = 'Ante.Configuration.BrandingConfiguration.GetConfiguration';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: BrandingConfiguration = {} as any;

    constructor() {
        super(BrandingConfiguration, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<BrandingConfiguration>, PerformQuery, SetSorting] {
        return useQuery<BrandingConfiguration, GetConfiguration>(GetConfiguration);
    }

    static useSuspense(): [QueryResultWithState<BrandingConfiguration>, PerformQuery, SetSorting] {
        return useSuspenseQuery<BrandingConfiguration, GetConfiguration>(GetConfiguration);
    }

    static when(condition: boolean): QueryWhen<GetConfiguration, BrandingConfiguration> {
        return new QueryWhen<GetConfiguration, BrandingConfiguration>(GetConfiguration, condition);
    }
}

/**
 * Response model for the host application URL configuration endpoint.
 */
export class HostAppUrlConfiguration {

    /**
     * The host application base URL template. Replace `{tenant}` with the tenant subdomain at runtime.
     */
    @field(String)
    hostAppUrl!: string;

    /**
     * The path on the host application that signs the current user in with the provider they are already using here, so crossing from the lobby to the host is a silent round trip instead of a second provider selection. The root path when the provider is unknown.
     */
    @field(String)
    signInPath!: string;
}

/**
 * Response model for lobby branding, driving dynamic rendering decisions in the frontend (logo, custom CSS).
 */
export class BrandingConfiguration {

    /**
     * The URL of a custom logo. When empty, a generic Ante wordmark is used.
     */
    @field(String)
    logoUrl!: string;

    /**
     * The URL of a custom CSS file to inject. When empty, the default lobby styles are used.
     */
    @field(String)
    customCssUrl!: string;
}
