// @generated by Cratis. Source: Ante.Configuration.HostAppUrlConfiguration, Ante.Configuration.BrandingConfiguration, Ante.Configuration.RegistrationConfiguration, Ante.Configuration.HostAppUrlConfiguration, Ante.Configuration.BrandingConfiguration, Ante.Configuration.RegistrationConfiguration, Ante.Configuration.RegistrationPageContent. Time: 2026-09-28T19:45:09.6567320Z. Hash: A0A499F76C4CAE7BB58A557095891AD2C765627D14A95ED5D327FFB6E0EF72AB
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Returns the {@link HostAppUrlConfiguration} based on the provided {@link AnteOptions} and the identity provider behind the current request.
 */
export class HostUrl extends QueryFor<HostAppUrlConfiguration> {
    readonly route: string = '/api/configuration/host-url';
    readonly queryName: string = 'Ante.Configuration.HostAppUrlConfiguration.HostUrl';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: HostAppUrlConfiguration = {} as HostAppUrlConfiguration;

    constructor() {
        super(HostAppUrlConfiguration, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<HostAppUrlConfiguration>, PerformQuery, SetSorting] {
        return useQuery<HostAppUrlConfiguration, HostUrl>(HostUrl);
    }

    static useSuspense(): [QueryResultWithState<HostAppUrlConfiguration>, PerformQuery, SetSorting] {
        return useSuspenseQuery<HostAppUrlConfiguration, HostUrl>(HostUrl);
    }

    static when(condition: boolean): QueryWhen<HostUrl, HostAppUrlConfiguration> {
        return new QueryWhen<HostUrl, HostAppUrlConfiguration>(HostUrl, condition);
    }
}

/**
 * Returns the {@link BrandingConfiguration} based on the provided {@link AnteOptions}.
 */
export class GetConfiguration extends QueryFor<BrandingConfiguration> {
    readonly route: string = '/api/configuration/get-configuration';
    readonly queryName: string = 'Ante.Configuration.BrandingConfiguration.GetConfiguration';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: BrandingConfiguration = {} as BrandingConfiguration;

    constructor() {
        super(BrandingConfiguration, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<BrandingConfiguration>, PerformQuery, SetSorting] {
        return useQuery<BrandingConfiguration, GetConfiguration>(GetConfiguration);
    }

    static useSuspense(): [QueryResultWithState<BrandingConfiguration>, PerformQuery, SetSorting] {
        return useSuspenseQuery<BrandingConfiguration, GetConfiguration>(GetConfiguration);
    }

    static when(condition: boolean): QueryWhen<GetConfiguration, BrandingConfiguration> {
        return new QueryWhen<GetConfiguration, BrandingConfiguration>(GetConfiguration, condition);
    }
}

/**
 * Gets the registration configuration for the current request's locale.
 */
export class Registration extends QueryFor<RegistrationConfiguration> {
    readonly route: string = '/api/configuration/registration';
    readonly queryName: string = 'Ante.Configuration.RegistrationConfiguration.Registration';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: RegistrationConfiguration = {} as RegistrationConfiguration;

    constructor() {
        super(RegistrationConfiguration, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<RegistrationConfiguration>, PerformQuery, SetSorting] {
        return useQuery<RegistrationConfiguration, Registration>(Registration);
    }

    static useSuspense(): [QueryResultWithState<RegistrationConfiguration>, PerformQuery, SetSorting] {
        return useSuspenseQuery<RegistrationConfiguration, Registration>(Registration);
    }

    static when(condition: boolean): QueryWhen<Registration, RegistrationConfiguration> {
        return new QueryWhen<Registration, RegistrationConfiguration>(Registration, condition);
    }
}

/**
 * Response model for the host application URL configuration endpoint.
 */
export class HostAppUrlConfiguration {

    /**
     * The host application base URL template. Replace `{tenant}` with the tenant subdomain at runtime.
     */
    @field(String)
    hostAppUrl!: string;

    /**
     * The path on the host application that signs the current user in with the provider they are already using here, so crossing from the lobby to the host is a silent round trip instead of a second provider selection. The root path when the provider is unknown.
     */
    @field(String)
    signInPath!: string;
}

/**
 * Response model for lobby branding, driving dynamic rendering decisions in the frontend (logo, custom CSS).
 */
export class BrandingConfiguration {

    /**
     * The URL of a custom logo. When empty, a generic Ante wordmark is used.
     */
    @field(String)
    logoUrl!: string;

    /**
     * The URL of a custom CSS file to inject. When empty, the default lobby styles are used.
     */
    @field(String)
    customCssUrl!: string;
}

/**
 * The host-authored copy for the registration page, resolved for the visitor's locale.
 */
export class RegistrationPageContent {

    /**
     * The heading replacing the default subtitle; empty keeps the default.
     */
    @field(String)
    title!: string;

    /**
     * Introductory or offer text; empty shows nothing.
     */
    @field(String)
    intro!: string;

    /**
     * Short highlight lines.
     */
    @field(String, true)
    highlights!: string[];

    /**
     * The host's pricing page; empty shows no link.
     */
    @field(String)
    pricingUrl!: string;

    /**
     * Where an existing user logs in instead; empty shows no link.
     */
    @field(String)
    loginUrl!: string;

    /**
     * The message shown while handing over to the host; empty keeps the default.
     */
    @field(String)
    completionMessage!: string;
}

/**
 * What the lobby needs to know about self-service registration before rendering `/register`.
 */
export class RegistrationConfiguration {

    /**
     * Whether this deployment offers self-service registration.
     */
    @field(Boolean)
    isEnabled!: boolean;

    /**
     * An optional link shown when registration is not offered.
     */
    @field(String)
    closedUrl!: string;

    /**
     * The query-string keys the lobby keeps from the registration link as signup context.
     */
    @field(String, true)
    contextKeys!: string[];

    /**
     * The host-authored copy for the visitor's locale.
     */
    @field(RegistrationPageContent)
    content!: RegistrationPageContent;
}
