// @generated by Cratis. Source: Ante.Configuration.HostAppUrlConfiguration, Ante.Configuration.BrandingConfiguration, Ante.Configuration.HostAppUrlConfiguration, Ante.Configuration.BrandingConfiguration. Time: 2026-09-27T17:22:07.6857970Z. Hash: 6B0461867D2674630AFF5DC34BFF8E9CD2A559D77499B55BD70685955E501C32
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/
/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { field } from '@cratis/fundamentals';

/**
 * Returns the {@link HostAppUrlConfiguration} based on the provided {@link AnteOptions} and the identity provider behind the current request.
 */
export class HostUrl extends QueryFor<HostAppUrlConfiguration> {
    readonly route: string = '/api/configuration/host-url';
    readonly queryName: string = 'Ante.Configuration.HostAppUrlConfiguration.HostUrl';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: HostAppUrlConfiguration = {} as HostAppUrlConfiguration;

    constructor() {
        super(HostAppUrlConfiguration, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<HostAppUrlConfiguration>, PerformQuery, SetSorting] {
        return useQuery<HostAppUrlConfiguration, HostUrl>(HostUrl);
    }

    static useSuspense(): [QueryResultWithState<HostAppUrlConfiguration>, PerformQuery, SetSorting] {
        return useSuspenseQuery<HostAppUrlConfiguration, HostUrl>(HostUrl);
    }

    static when(condition: boolean): QueryWhen<HostUrl, HostAppUrlConfiguration> {
        return new QueryWhen<HostUrl, HostAppUrlConfiguration>(HostUrl, condition);
    }
}

/**
 * Returns the {@link BrandingConfiguration} based on the provided {@link AnteOptions}.
 */
export class GetConfiguration extends QueryFor<BrandingConfiguration> {
    readonly route: string = '/api/configuration/get-configuration';
    readonly queryName: string = 'Ante.Configuration.BrandingConfiguration.GetConfiguration';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: BrandingConfiguration = {} as BrandingConfiguration;

    constructor() {
        super(BrandingConfiguration, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<BrandingConfiguration>, PerformQuery, SetSorting] {
        return useQuery<BrandingConfiguration, GetConfiguration>(GetConfiguration);
    }

    static useSuspense(): [QueryResultWithState<BrandingConfiguration>, PerformQuery, SetSorting] {
        return useSuspenseQuery<BrandingConfiguration, GetConfiguration>(GetConfiguration);
    }

    static when(condition: boolean): QueryWhen<GetConfiguration, BrandingConfiguration> {
        return new QueryWhen<GetConfiguration, BrandingConfiguration>(GetConfiguration, condition);
    }
}

/**
 * Response model for the host application URL configuration endpoint.
 */
export class HostAppUrlConfiguration {

    /**
     * The host application base URL template. Replace `{tenant}` with the tenant subdomain at runtime.
     */
    @field(String)
    hostAppUrl!: string;

    /**
     * The path on the host application that signs the current user in with the provider they are already using here, so crossing from the lobby to the host is a silent round trip instead of a second provider selection. The root path when the provider is unknown.
     */
    @field(String)
    signInPath!: string;
}

/**
 * Response model for lobby branding, driving dynamic rendering decisions in the frontend (logo, custom CSS).
 */
export class BrandingConfiguration {

    /**
     * The URL of a custom logo. When empty, a generic Ante wordmark is used.
     */
    @field(String)
    logoUrl!: string;

    /**
     * The URL of a custom CSS file to inject. When empty, the default lobby styles are used.
     */
    @field(String)
    customCssUrl!: string;
}
